#!/usr/bin/env bash
info_custom ()
{
    for arg
    do
	echo -n "The subdomain $arg is a "
	dig $arg."$domain" | grep -A1 'ANSWER SECTION:' | tail -n 1 | awk '{print $4 " record and points to " $5}'
    done
}

domain="$1"
if [ $# -eq 1 ]; then
    info_custom www lb-01 web-01 web-02
else
    sbdmain="$2"
    info_custom "$sbdmain"
fi
