#!/usr/bin/env bash
# transfers a file from our client to a server.
file=$1
pathkey=$2
ip=$3
user=$4
if [ $# -lt 3 ]
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
elif [ $# -eq 3 ]
then
    scp -o StrictHostKeyChecking=no "$file" "$user@$ip:~/"
else
    scp -o StrictHostKeyChecking=no -i "$pathkey" "$file" "$user@$ip:~/"
fi
