#!/usr/bin/env bash
# Install Nginx and Configure
# Update Sever
sudo apt-get update -y
sudo apt-get install nginx -y
echo "Holberton School" > /var/www/html/index.nginx-debian.html
service nginx start
