#!/usr/bin/env bash
# Configures NGINX
apt-get update
apt-get -y install nginx
echo "Holberton School" | tee /usr/share/nginx/html/index.html
URL=/etc/nginx/sites-available/default
RED="location /redirect_me {\n return 301 https://www.youtube.com/watch?v=POglcuW-Rb4;\n}\n"
sed -i "37i $RED" $URL
service nginx restart
