#!/usr/bin/env bash
# Configure the Nginx server to have a custom 404 page that contains a custom string
apt-get update -y
apt-get install nginx -y
echo "Holberton School" > /var/www/html/index.nginx-debian.html
red="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=POglcuW-Rb4;\n\t}\n"
sed -i "37i\ $red" /var/www/html/custom_404.html
p404="\n\terror_page 404 /custom_404.html;\n\tlocation = /custom_404.html {\n\t\troot /var/www/html;\n\t\tinternal;\n\t}\n"
echo "Ceci n'est pas une page" | tee /usr/share/nginx/html/index.html
sed -i "37i\ $p404" /etc/nginx/sites-available/default
service nginx restart
