#!/usr/bin/env bash
# Displays To infinity and beyond indefinitely
# Displays I hate the kill command when receiving a SIGTERM signal
# Displays Y U no love me?! when receiving a SIGINT signal
# Deletes the file /var/run/holbertonscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
pid="/var/run/holbertonscript.pid"
echo $$ > /var/run/holbertonscript.pid
    trap 'echo "I hate the kill command"; rm -rf $pid; exit 0' SIGTERM
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'rm -rf $pid; exit 0' SIGQUIT
while true
do
    echo "To infinity and beyond"
    sleep 2
done
