#!/usr/bin/env bash
# Displays the time for 12 hours and 59 minutes.
let hours=0
let minutes=1
while [ $hours -le 12 ];
do
    echo "Hour: $hours"
    while [ $minutes -le 59 ];
    do
        echo "$minutes"
        let minutes=minutes+1
    done
    let minutes=1
    let hours=hours+1
done
